### ISSUE TITLE
Duplicate person error- is this the intended behaviour?

### ISSUE THREAD

**Issue by lingyanhao** [nus-cs2103-AY1819S2/forum#40]
AB4 is designed to not allow duplicate entries in the book. However, the following sequence of commands result in a strange exception being thrown:

`add n/aaa p/123 e/a@a.a a/address`
Output: "New person added: aaa Phone: 123 Email: a@a.a Address: address Tags:" (expected)
`add n/aaa p/234 e/b@b.b a/address`
Output: "New person added: aaa Phone: 234 Email: b@b.b Address: address Tags:" (expected)
`edit 8 p/123`

Now an exception is thrown

Caused by: seedu.address.model.person.exceptions.DuplicatePersonException: Operation would result in duplicate persons
	at seedu.address.model.person.UniquePersonList.setPersons(UniquePersonList.java:94)
	at seedu.address.model.AddressBook.setPersons(AddressBook.java:50)
	at seedu.address.model.AddressBook.resetData(AddressBook.java:60)
	at seedu.address.model.AddressBook.<init>(AddressBook.java:40)
	at seedu.address.model.VersionedAddressBook.commit(VersionedAddressBook.java:28)
	at seedu.address.model.ModelManager.commitAddressBook(ModelManager.java:163)
	at seedu.address.logic.commands.EditCommand.execute(EditCommand.java:87)
	at seedu.address.logic.LogicManager.execute(LogicManager.java:52)
	at seedu.address.ui.MainWindow.executeCommand(MainWindow.java:182)
	at seedu.address.ui.CommandBox.handleCommandEntered(CommandBox.java:101)

Is this a AB4 bug or is this the intended behavior?

**Comment by okkhoy** [comment]
I won't answer this question, dig a bit around the code and you can figure out 😜 
You can update the behavior if you wish.

**Comment by pyokagan** [comment]
@lingyanhao 
> Is this a AB4 bug or is this the intended behavior?

It's a bug, please file an issue at https://github.com/se-edu/addressbook-level4/issues

Turns out that the `isSamePerson` relation is NOT transitive, while our code assumes it to be so.

Of course, a PR that solves this nicely (without depending on any internal details of `isSamePerson`) would be nice too :-)
